INSERT INTO movie(id, user_id, movie_name, category, genre, episodes) VALUES (15001, 1, 'Toy Story','Movie', 'Adventure', '1' );
INSERT INTO movie(id, user_id, movie_name, category, genre, episodes) VALUES (15002, 1, 'Mulan','Movie', 'Adventure', '1' );
INSERT INTO movie(id, user_id, movie_name, category, genre, episodes) VALUES (15003, 1, 'Inception','Movie', 'Adventure', '1' );
INSERT INTO movie(id, user_id, movie_name, category, genre, episodes) VALUES (15004, 1, 'Cars','Movie', 'Adventure', '1' );
INSERT INTO movie(id, user_id, movie_name, category, genre, episodes) VALUES (15005, 1,'Jurassic Park','Movie', 'Adventure', '1' );
INSERT INTO movie(id, user_id, movie_name, category, genre, episodes) VALUES (15006, 1, 'Snow Fall','Web-series', 'Thriller', '40' );
INSERT INTO movie(id, user_id, movie_name, category, genre, episodes) VALUES (15007, 1, 'The Irishman','Movie', 'Thriller', '1' );
INSERT INTO movie(id, user_id, movie_name, category, genre, episodes) VALUES (15008, 1, 'Parasite','Movie', 'Thriller', '1' );
INSERT INTO movie(id, user_id, movie_name, category, genre, episodes) VALUES (15009, 1, 'Avengers','Movie', 'Adventure', '1' );
INSERT INTO review(id,movie_id, user_id, rating, description) VALUES (1001, 15001, 1, 10, 'Childhood favorite movie, watched a million times and never gets old!');
INSERT INTO review(id,movie_id, user_id, rating, description) VALUES (1002, 15002, 1, 10, 'Great movie with lots of good music.');
INSERT INTO review(id,movie_id, user_id, rating, description) VALUES (1003, 15003, 1, 10, 'Leonardo DiCaprio is all!!!');
INSERT INTO review(id,movie_id, user_id, rating, description) VALUES (1004, 15004, 1, 10, 'Funny movie');
INSERT INTO review(id,movie_id, user_id, rating, description) VALUES (1005, 15005, 1, 10, 'Classic, must watch');
INSERT INTO review(id,movie_id, user_id, rating, description) VALUES (1006, 15006, 1, 10, 'Definitely not about snow');
INSERT INTO review(id,movie_id, user_id, rating, description) VALUES (1007, 15007, 1, 10, 'Must see');
INSERT INTO review(id,movie_id, user_id, rating, description) VALUES (1008, 15008, 1, 10, 'Lots of twists thatll keep you on your feet');
INSERT INTO review(id,movie_id, user_id, rating, description) VALUES (1009, 15009, 1, 10, 'This is where it all started');