INSERT INTO movie(id, movie_name, category, genre, episodes) VALUES (15001, 'Toy Story','Movie', 'Adventure', '1' )
INSERT INTO movie(id, movie_name, category, genre, episodes) VALUES (15002, 'Mulan','Movie', 'Adventure', '1' )
INSERT INTO movie(id, movie_name, category, genre, episodes) VALUES (15003, 'Inception','Movie', 'Adventure', '1' )
INSERT INTO movie(id, movie_name, category, genre, episodes) VALUES (15004, 'Cars','Movie', 'Adventure', '1' )
INSERT INTO movie(id, movie_name, category, genre, episodes) VALUES (15005, 'Jurassic Park','Movie', 'Adventure', '1' )